### ISSUE TITLE
Shipped jQuery 1.12.4 breaks my own jQuery

### ISSUE THREAD

**Issue by peterkraume** [Konafets/typo3_debugbar#5] opened 2018-02-23 22:22 UTC
EXT:typo3_debugbar ships with `Resources/Public/JavaScript/debugbar.js` which includes jQuery 1.12.4. This breaks the jQuery that I've included in my theme extension.

Do you have any idea how to approach this problem. Maybe you can add a possibility to make the jQuery inclusion optional?

**Comment by Konafets** [comment] 2018-02-24 22:29
Debugbar.js comes from the upstream lib. Need to look into it.

**Comment by Konafets** [comment] 2018-03-05 15:28
@peterkraume Can you check latest version of develop branch? Let me know if the issue is fixed.

**Comment by Konafets** [comment] 2018-03-07 19:12
Fixed in 8819824de358415e1d2c0eea11b0c7c34cec4e0c

**Closed as completed** 2018-03-08 08:42 UTC
Labels: bug, question

**Comment by peterkraume** [comment] 2018-03-09 21:53
Sorry, wasn't able to test earlier. I've now tested version 1.2.0 and it seems to run smoothly. Thx for the solution.
